<a href="https://colab.research.google.com/github/RafigaAllahverdizade/Pandas_Project/blob/main/Pandas_ipynb_adl%C4%B1_not_defterinin_kopyas%C4%B1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Find and remove duplicate values (and describe why you make your choices)

In [1]:
import pandas as pd

### `orders` data frame

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
# Check for duplicated orders
products_order = pd.read_csv("/content/drive/MyDrive/Pandas_Project_2/order_products.csv", sep = ";")
products_order.head()

   order_id  product_id  add_to_cart_order  reordered
0   2141543       11440               17.0          0
1    567889        1560                1.0          1
2   2261212       26683                1.0          1
3    491251        8670               35.0          1
4   2571142        1940                5.0          1

What each column represents:

1.   'order_id'- ID number that uniquely identifies each order
2.   'product_id'- ID number that uniquely identifies each product
3.   'add_to_cart_order'- the sequential order in which each item was placed in the cart
4.   'reordered'- 0 if the customer has never ordered this product before, 1 if they have

In [4]:
products_order.shape

(4545007, 4)

In [5]:
products_data = pd.read_csv("/content/drive/MyDrive/Pandas_Project_2/products.csv", sep = ";")
products_data.head()

,product_id,product_name,aisle_id,department_id
0,1,Chocolate Sandwich Cookies,61,19
1,2,All-Seasons Salt,104,13
2,3,Robust Golden Unsweetened Oolong Tea,94,7
3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,38,1
4,5,Green Chile Anytime Sauce,5,13

What each column represent:


1.   'product_id': ID number that uniquely identifies each product
2.   'product_name': name of the product
3.   'aisle_id': ID number that uniquely identifies each grocery aisle category
4.   'department_id': ID number that uniquely identifies each grocery department category

In [6]:
products_data.shape

(49694, 4)

In [7]:
departments_data = pd.read_csv("/content/drive/MyDrive/Pandas_Project_2/departments.csv", sep = ";")
departments_data.head()

   department_id department
0              1     frozen
1              2      other
2              3     bakery
3              4    produce
4              5    alcohol

What each column represent:


1.   'department_id': ID number that uniquely identifies each grocery department category
2.   'department': name of the department

In [8]:
departments_data.shape

(21, 2)

In [9]:
aisles_data = pd.read_csv("/content/drive/MyDrive/Pandas_Project_2/aisles.csv", sep = ";")
aisles_data.head()

   aisle_id                       aisle
0         1       prepared soups salads
1         2           specialty cheeses
2         3         energy granola bars
3         4               instant foods
4         5  marinades meat preparation

What each column represent:


1.   'aisle_id': ID number that uniquely identifies each grocery aisle category
2.   'aisle': name of the aisle

In [10]:
aisles_data.shape

(134, 2)

In [11]:
orders_instacart = pd.read_csv("/content/drive/MyDrive/Pandas_Project_2/instacart_orders.csv", sep = ";")
orders_instacart.head()

,order_id,user_id,order_number,order_dow,order_hour_of_day,days_since_prior_order
0,1515936,183418,11,6,13,30.0
1,1690866,163593,5,5,12,9.0
2,1454967,39980,4,5,19,2.0
3,1768857,82516,56,0,20,10.0
4,3007858,196724,2,4,12,17.0

What each column represents:


1.   'order_id': ID number that uniquely identifies each order
2.   'user_id': ID number that uniquely identifies each customer account
3.   'order_number': the number of times this customer has placed an order
4.   'order_dow': day of the week that the order placed
5.   'order_hour_of_day': hour of the day that the order was placed
6.   'days_since_prior_order': number of days since this customer placed their previous order

In [12]:
orders_instacart.shape

(478967, 6)

In [13]:
#For easy analysis, we merge all data with "outer" for not to lose any of our data.
df = pd.DataFrame(products_order)
data_join = df.merge(products_data, on = "product_id", how = "outer")
data_join = data_join.merge(departments_data, on = "department_id", how = "outer")
data_join = data_join.merge(aisles_data, on = "aisle_id", how = "outer")
data_join = data_join.merge(orders_instacart, on = "order_id", how = "outer")
df = data_join
df.head()

,order_id,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,department,aisle,user_id,order_number,order_dow,order_hour_of_day,days_since_prior_order
0,4.0,39758.0,3.0,1.0,Chewy 25% Low Sugar Chocolate Chip Granola,3.0,19.0,snacks,energy granola bars,178520.0,36.0,1.0,9.0,7.0
1,4.0,26434.0,2.0,1.0,Honey/Lemon Cough Drops,11.0,11.0,personal care,cold flu allergy,178520.0,36.0,1.0,9.0,7.0
2,4.0,25146.0,11.0,1.0,Original Orange Juice,31.0,7.0,beverages,refrigerated,178520.0,36.0,1.0,9.0,7.0
3,4.0,10054.0,5.0,1.0,Kellogg's Nutri-Grain Apple Cinnamon Cereal,48.0,14.0,breakfast,breakfast bars pastries,178520.0,36.0,1.0,9.0,7.0
4,4.0,21351.0,6.0,1.0,Nutri-Grain Soft Baked Strawberry Cereal Break...,48.0,14.0,breakfast,breakfast bars pastries,178520.0,36.0,1.0,9.0,7.0

In [14]:
df.shape

(4578180, 14)

In [15]:
#This code exactly help us to identify non-missing data in each column. As a result we see that there is missing data almost in every column.
df.info(show_counts = True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4578180 entries, 0 to 4578179
Data columns (total 14 columns):
 #   Column                  Non-Null Count    Dtype
---  ------                  --------------    -----
 0   order_id                4574059 non-null  float64
 1   product_id              4549274 non-null  float64
 2   add_to_cart_order       4544317 non-null  float64
 3   reordered               4545153 non-null  float64
 4   product_name            4539429 non-null  object
 5   aisle_id                4549274 non-null  float64
 6   department_id           4549274 non-null  float64
 7   department              4549274 non-null  object
 8   aisle                   4549274 non-null  object
 9   user_id                 4574059 non-null  float64
 10  order_number            4574059 non-null  float64
 11  order_dow               4574059 non-null  float64
 12  order_hour_of_day       4574059 non-null  float64
 13  days_since_prior_order  4282115 non-null  float64
dtypes: float64(11), object(3)
memory usage: 489.0+ MB

In [16]:
df = df.apply(lambda x: x.str.lower() if x.dtype == "object" else x)
df.head()

,order_id,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,department,aisle,user_id,order_number,order_dow,order_hour_of_day,days_since_prior_order
0,4.0,39758.0,3.0,1.0,chewy 25% low sugar chocolate chip granola,3.0,19.0,snacks,energy granola bars,178520.0,36.0,1.0,9.0,7.0
1,4.0,26434.0,2.0,1.0,honey/lemon cough drops,11.0,11.0,personal care,cold flu allergy,178520.0,36.0,1.0,9.0,7.0
2,4.0,25146.0,11.0,1.0,original orange juice,31.0,7.0,beverages,refrigerated,178520.0,36.0,1.0,9.0,7.0
3,4.0,10054.0,5.0,1.0,kellogg's nutri-grain apple cinnamon cereal,48.0,14.0,breakfast,breakfast bars pastries,178520.0,36.0,1.0,9.0,7.0
4,4.0,21351.0,6.0,1.0,nutri-grain soft baked strawberry cereal break...,48.0,14.0,breakfast,breakfast bars pastries,178520.0,36.0,1.0,9.0,7.0

In [17]:
df.duplicated().sum()

np.int64(146)

In [18]:
#With this code, checked that every order has a duplicated order as well. Since the products can be reordered again, however, it has to appear once in the dataset as a reorder.
df[df.duplicated(keep=False)]

,order_id,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,department,aisle,user_id,order_number,order_dow,order_hour_of_day,days_since_prior_order
516940,391768.0,39619.0,5.0,0.0,organic tomato basil pasta sauce,9.0,9.0,dry goods pasta,pasta sauce,57671.0,19.0,3.0,2.0,10.0
516941,391768.0,39619.0,5.0,0.0,organic tomato basil pasta sauce,9.0,9.0,dry goods pasta,pasta sauce,57671.0,19.0,3.0,2.0,10.0
516942,391768.0,26604.0,3.0,1.0,organic blackberries,24.0,4.0,produce,fresh fruits,57671.0,19.0,3.0,2.0,10.0
516943,391768.0,26604.0,3.0,1.0,organic blackberries,24.0,4.0,produce,fresh fruits,57671.0,19.0,3.0,2.0,10.0
516944,391768.0,25890.0,1.0,1.0,boneless skinless chicken breasts,49.0,12.0,meat seafood,packaged poultry,57671.0,19.0,3.0,2.0,10.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3809054,2845099.0,13166.0,1.0,1.0,organic milk reduced fat- 2% milkfat,84.0,16.0,dairy eggs,milk,31189.0,11.0,3.0,2.0,7.0
3809055,2845099.0,28986.0,7.0,0.0,mild italian chicken sausage,106.0,12.0,meat seafood,hot dogs bacon sausage,31189.0,11.0,3.0,2.0,7.0
3809056,2845099.0,28986.0,7.0,0.0,mild italian chicken sausage,106.0,12.0,meat seafood,hot dogs bacon sausage,31189.0,11.0,3.0,2.0,7.0
3809057,2845099.0,43154.0,3.0,1.0,sparkling mineral water,115.0,7.0,beverages,water seltzer sparkling water,31189.0,11.0,3.0,2.0,7.0
3809058,2845099.0,43154.0,3.0,1.0,sparkling mineral water,115.0,7.0,beverages,water seltzer sparkling water,31189.0,11.0,3.0,2.0,7.0

In [19]:
# Remove duplicate orders
df.drop_duplicates(inplace = True)
df.shape

(4578034, 14)

In [20]:
# Check for all orders placed Wednesday at 2:00 AM
df[(df["order_dow"] == 2) & (df["order_hour_of_day"] == 2)]

,order_id,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,department,aisle,user_id,order_number,order_dow,order_hour_of_day,days_since_prior_order
7970,5825.0,10305.0,4.0,1.0,black plum,24.0,4.0,produce,fresh fruits,79768.0,2.0,2.0,2.0,8.0
7971,5825.0,29941.0,2.0,0.0,red plums,24.0,4.0,produce,fresh fruits,79768.0,2.0,2.0,2.0,8.0
7972,5825.0,17615.0,5.0,0.0,calcium pulp free orange juice,31.0,7.0,beverages,refrigerated,79768.0,2.0,2.0,2.0,8.0
7973,5825.0,13410.0,3.0,1.0,white cherry sports drink,64.0,7.0,beverages,energy sports drinks,79768.0,2.0,2.0,2.0,8.0
7974,5825.0,15221.0,1.0,0.0,2% milk,84.0,16.0,dairy eggs,milk,79768.0,2.0,2.0,2.0,8.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4525912,3385358.0,12980.0,2.0,1.0,large greenhouse tomato,83.0,4.0,produce,fresh vegetables,164049.0,3.0,2.0,2.0,30.0
4525913,3385358.0,28993.0,3.0,1.0,iceberg lettuce,83.0,4.0,produce,fresh vegetables,164049.0,3.0,2.0,2.0,30.0
4525914,3385358.0,25155.0,4.0,1.0,blended strawberry yogurt,120.0,16.0,dairy eggs,yogurt,164049.0,3.0,2.0,2.0,30.0
4525915,3385358.0,37228.0,1.0,1.0,mango lowfat kefir,120.0,16.0,dairy eggs,yogurt,164049.0,3.0,2.0,2.0,30.0
4525916,3385358.0,41373.0,5.0,1.0,original smooth style strawberry flavored low ...,120.0,16.0,dairy eggs,yogurt,164049.0,3.0,2.0,2.0,30.0

In [21]:
# Double check for duplicate rows
df.duplicated().sum()

np.int64(0)

In [22]:
# Double check for duplicate order IDs only
df.duplicated(subset = "order_id").sum()

np.int64(4099081)

In [23]:
df_order_ID_duplicated = df[df.duplicated(subset = "order_id", keep = False)]
df_order_ID_duplicated.head()

,order_id,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,department,aisle,user_id,order_number,order_dow,order_hour_of_day,days_since_prior_order
0,4.0,39758.0,3.0,1.0,chewy 25% low sugar chocolate chip granola,3.0,19.0,snacks,energy granola bars,178520.0,36.0,1.0,9.0,7.0
1,4.0,26434.0,2.0,1.0,honey/lemon cough drops,11.0,11.0,personal care,cold flu allergy,178520.0,36.0,1.0,9.0,7.0
2,4.0,25146.0,11.0,1.0,original orange juice,31.0,7.0,beverages,refrigerated,178520.0,36.0,1.0,9.0,7.0
3,4.0,10054.0,5.0,1.0,kellogg's nutri-grain apple cinnamon cereal,48.0,14.0,breakfast,breakfast bars pastries,178520.0,36.0,1.0,9.0,7.0
4,4.0,21351.0,6.0,1.0,nutri-grain soft baked strawberry cereal break...,48.0,14.0,breakfast,breakfast bars pastries,178520.0,36.0,1.0,9.0,7.0

In [24]:
df_order_ID_duplicated.shape

(4527281, 14)

In [25]:
order_summary = (df_order_ID_duplicated.groupby("order_id").agg(n_products=("product_id", "count"), n_reordered=("reordered", "sum")).reset_index())
order_summary.head()

   order_id  n_products  n_reordered
0       4.0          13         12.0
1       9.0          15         10.0
2      11.0           5          5.0
3      19.0           3          3.0
4      20.0           8          0.0

In [26]:
df_order_ID_duplicated.shape

(4527281, 14)

In [27]:
#Each product ID is unique for order IDs. There is no duplications.
duplicate_order_products = df[df.duplicated(subset=["order_id", "product_id"], keep=False)]
duplicate_order_products

Empty DataFrame
Columns: [order_id, product_id, add_to_cart_order, reordered, product_name, aisle_id, department_id, department, aisle, user_id, order_number, order_dow, order_hour_of_day, days_since_prior_order]
Index: []

To check whether the duplicated order IDs are valid or they have to be corrected, I just tried to check via product IDs and reorders. Since if one product is already ordered, it cannot be ordered with the same order ID again. Instead it has to be mentioned as 1 in reorders column. I believe there is no need to make some cleaning process in Order ID column.

### `products` data frame

In [28]:
# Check for fully duplicate rows
df_products = pd.DataFrame(products_data)
df_products = df_products.apply(lambda x: x.str.lower() if x.dtype == "object" else x)
df_products.duplicated().sum()

np.int64(0)

In [29]:
# Check for just duplicate product IDs
product_IDS = df_products["product_id"]
product_IDS.duplicated().sum()

np.int64(0)

In [30]:
# Check for just duplicate product names (convert names to lowercase to compare better)
# This code treats missing values as duplicates as well.
df_products["product_name"] = df_products["product_name"].str.lower()
product_names = df_products["product_name"]
product_names.duplicated().sum()

np.int64(1361)

In [31]:
product_names_clean = df_products["product_name"].dropna()
true_duplicates = product_names_clean.duplicated().sum()
true_duplicates

np.int64(104)

In [32]:
duplicated_products = df_products[df_products.duplicated(subset = "product_name", keep = False)]
duplicated_products

,product_id,product_name,aisle_id,department_id
37,38,NaN,100,21
41,42,biotin 1000 mcg,47,11
71,72,NaN,100,21
109,110,NaN,100,21
185,186,fresh scent dishwasher detergent with dawn,74,17
...,...,...,...,...
49689,49690,high performance energy drink,64,7
49690,49691,original pancake & waffle mix,130,14
49691,49692,organic instant oatmeal light maple brown sugar,130,14
49692,49693,spring water body wash,127,11
49693,49694,burrito- steak & cheese,38,1

In [33]:
duplicated_products["product_name"].isna().sum()

np.int64(1258)

In [34]:
real_duplicated_products = duplicated_products[duplicated_products["product_name"].notna()]
real_duplicated_products

,product_id,product_name,aisle_id,department_id
41,42,biotin 1000 mcg,47,11
185,186,fresh scent dishwasher detergent with dawn,74,17
515,516,american cheese slices,21,16
1538,1539,cauliflower head,83,4
1783,1784,nutrition protein mix blueberry nut,117,19
...,...,...,...,...
49689,49690,high performance energy drink,64,7
49690,49691,original pancake & waffle mix,130,14
49691,49692,organic instant oatmeal light maple brown sugar,130,14
49692,49693,spring water body wash,127,11
49693,49694,burrito- steak & cheese,38,1

In [35]:
df_products.head()

,product_id,product_name,aisle_id,department_id
0,1,chocolate sandwich cookies,61,19
1,2,all-seasons salt,104,13
2,3,robust golden unsweetened oolong tea,94,7
3,4,smart ones classic favorites mini rigatoni wit...,38,1
4,5,green chile anytime sauce,5,13

In [36]:
# Check for duplicate product names that aren't missing
df_products[df_products["product_name"].notna() & df_products["product_name"].duplicated()]

,product_id,product_name,aisle_id,department_id
2058,2059,biotin 1000 mcg,47,11
5455,5456,green tea with ginseng and honey,96,20
5558,5559,cream of mushroom soup,69,15
7558,7559,cinnamon rolls with icing,105,13
9037,9038,american cheese slices,21,16
...,...,...,...,...
49689,49690,high performance energy drink,64,7
49690,49691,original pancake & waffle mix,130,14
49691,49692,organic instant oatmeal light maple brown sugar,130,14
49692,49693,spring water body wash,127,11
49693,49694,burrito- steak & cheese,38,1

### `departments` data frame

In [37]:
df_departments = pd.DataFrame(departments_data)
df_departments = df_departments.apply(lambda x: x.str.lower() if x.dtype == "object" else x)
df_departments.head()

   department_id department
0              1     frozen
1              2      other
2              3     bakery
3              4    produce
4              5    alcohol

In [38]:
df_departments.duplicated().sum()

np.int64(0)

### `aisles` data frame

In [39]:
df_aisles = pd.DataFrame(aisles_data)
df_aisles = df_aisles.apply(lambda x: x.str.lower() if x.dtype == "object" else x)
df_aisles.head()

   aisle_id                       aisle
0         1       prepared soups salads
1         2           specialty cheeses
2         3         energy granola bars
3         4               instant foods
4         5  marinades meat preparation

In [40]:
df_aisles.duplicated().sum()

np.int64(0)

### `order_products` data frame

In [41]:
# Check for fullly duplicate rows
df_products_order = pd.DataFrame(products_order)
df_products_order = df_products_order.apply(lambda x: x.str.lower() if x.dtype == "object" else x)
df_products_order.duplicated().sum()

np.int64(0)

In [42]:
# Double check for any other tricky duplicates
df_products_order.duplicated(subset = "product_id").sum()

np.int64(4499434)

## Find and remove missing values

### `products` data frame

In [43]:
df_products_aisles = df_products.merge(df_aisles, on = "aisle_id", how = "outer")
df_products_aisles

,product_id,product_name,aisle_id,department_id,aisle
0,209,italian pasta salad,1,20,prepared soups salads
1,554,turkey chili,1,20,prepared soups salads
2,886,whole grain salad with roasted pecans & mango ...,1,20,prepared soups salads
3,1600,mediterranean orzo salad,1,20,prepared soups salads
4,2539,original potato salad,1,20,prepared soups salads
...,...,...,...,...,...
49689,47713,sparkling rose,134,5,specialty wines champagnes
49690,48984,dry sherry,134,5,specialty wines champagnes
49691,49438,dry fino sherry,134,5,specialty wines champagnes
49692,49562,blanc de noirs sparkling wine,134,5,specialty wines champagnes
49693,49661,porto,134,5,specialty wines champagnes

In [44]:
# Are all of the missing product names associated with aisle ID 100?
(df_products_aisles[df_products_aisles["product_name"].isna()]["aisle_id"] == 100).all()

np.True_

In [45]:
(df_products_aisles[df_products_aisles["product_name"].isna()]["aisle_id"] == 100).sum()

np.int64(1258)

In [46]:
# Are all of the missing product names associated with department ID 21?
df_products_departments = df_products.merge(df_departments, on = "department_id", how = "outer")
(df_products_departments[df_products_departments["product_name"].isna()]["department_id"] == 21).all()

np.True_

In [47]:
(df_products_departments[df_products_departments["product_name"].isna()]["department_id"] == 21).sum()

np.int64(1258)

In [48]:
# What is this ailse and department?
df_products.isna().sum()

product_id          0
product_name     1258
aisle_id            0
department_id       0
dtype: int64

In [49]:
df_missing_product_names = df_products.merge(df_aisles, on = "aisle_id", how = "outer")
df_missing_product_names = df_missing_product_names.merge(df_departments, on = "department_id", how = "outer")
df_missing_product_names[df_missing_product_names["product_name"].isna()]

       product_id product_name  aisle_id  department_id    aisle department
48436          38          NaN       100             21  missing    missing
48437          72          NaN       100             21  missing    missing
48438         110          NaN       100             21  missing    missing
48439         297          NaN       100             21  missing    missing
48440         417          NaN       100             21  missing    missing
...           ...          ...       ...            ...      ...        ...
49689       49553          NaN       100             21  missing    missing
49690       49575          NaN       100             21  missing    missing
49691       49641          NaN       100             21  missing    missing
49692       49664          NaN       100             21  missing    missing
49693       49669          NaN       100             21  missing    missing

[1258 rows x 6 columns]

I just wanted to check the reason why the product names are anly missing in aisle ID "100" and department ID "21". However, it is noticed that aisle and department information is as well missing. Since in this case we cannot make any assumption regarding the missing product names.

In [50]:
# Fill missing product names with 'Unknown'
df_products["product_name"].fillna("Unknown", inplace = True)
df_products.isna().sum()

product_id       0
product_name     0
aisle_id         0
department_id    0
dtype: int64

### `orders` data frame

In [51]:
df

,order_id,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,department,aisle,user_id,order_number,order_dow,order_hour_of_day,days_since_prior_order
0,4.0,39758.0,3.0,1.0,chewy 25% low sugar chocolate chip granola,3.0,19.0,snacks,energy granola bars,178520.0,36.0,1.0,9.0,7.0
1,4.0,26434.0,2.0,1.0,honey/lemon cough drops,11.0,11.0,personal care,cold flu allergy,178520.0,36.0,1.0,9.0,7.0
2,4.0,25146.0,11.0,1.0,original orange juice,31.0,7.0,beverages,refrigerated,178520.0,36.0,1.0,9.0,7.0
3,4.0,10054.0,5.0,1.0,kellogg's nutri-grain apple cinnamon cereal,48.0,14.0,breakfast,breakfast bars pastries,178520.0,36.0,1.0,9.0,7.0
4,4.0,21351.0,6.0,1.0,nutri-grain soft baked strawberry cereal break...,48.0,14.0,breakfast,breakfast bars pastries,178520.0,36.0,1.0,9.0,7.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4578175,NaN,29951.0,NaN,NaN,ruby port wine,134.0,5.0,alcohol,specialty wines champagnes,NaN,NaN,NaN,NaN,NaN
4578176,NaN,30582.0,NaN,NaN,natural champagne,134.0,5.0,alcohol,specialty wines champagnes,NaN,NaN,NaN,NaN,NaN
4578177,NaN,34938.0,NaN,NaN,côtes-du-rhône,134.0,5.0,alcohol,specialty wines champagnes,NaN,NaN,NaN,NaN,NaN
4578178,NaN,39611.0,NaN,NaN,blackberry merlot wine,134.0,5.0,alcohol,specialty wines champagnes,NaN,NaN,NaN,NaN,NaN
4578179,NaN,44956.0,NaN,NaN,red moscato,134.0,5.0,alcohol,specialty wines champagnes,NaN,NaN,NaN,NaN,NaN

In [52]:
# Are there any missing values where it's not a customer's first order?
df[df["reordered"] == 1]["days_since_prior_order"].isna().sum()

np.int64(0)

### `order_products` data frame

In [53]:
df_products_order.head()

   order_id  product_id  add_to_cart_order  reordered
0   2141543       11440               17.0          0
1    567889        1560                1.0          1
2   2261212       26683                1.0          1
3    491251        8670               35.0          1
4   2571142        1940                5.0          1

In [54]:
# What are the min and max values in this column?
df_min = df_products_order["add_to_cart_order"].min()
df_max = df_products_order["add_to_cart_order"].max()
print(df_min)
print(df_max)

1.0
64.0

In [86]:
# Save all order IDs with at least one missing value in 'add_to_cart_order'
missing_order_ids = df_products_order[df_products_order["add_to_cart_order"].isna()]["order_id"]
missing_order_ids.head()

737      2449164
9926     1968313
14394    2926893
16418    1717990
30114    1959075
Name: order_id, dtype: int64

In [103]:
# Do all orders with missing values have more than 64 products?
greater_than_64 = (df_products_order[df_products_order["order_id"].isin(missing_order_ids)].groupby("order_id")["product_id"].count()).all()
greater_than_64

np.True_

In [104]:
# Replace missing values with 999 and convert column to integer type
df["add_to_cart_order"] = (df["add_to_cart_order"].fillna(999).astype(int))
df_products_order.sample(5)

         order_id  product_id  add_to_cart_order  reordered
1426375   1379117       28449                4.0          0
103962     475063       38797                6.0          0
2677210   1990736       20114                4.0          0
3662506   1926955        7923               22.0          0
3773418    741932        1541               13.0          1

In [105]:
df_products_order.max()

order_id             3421079.0
product_id             49694.0
add_to_cart_order         64.0
reordered                  1.0
dtype: float64

In [106]:
df.head()

,order_id,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,department,aisle,user_id,order_number,order_dow,order_hour_of_day,days_since_prior_order
0,4.0,39758.0,3,1.0,chewy 25% low sugar chocolate chip granola,3.0,19.0,snacks,energy granola bars,178520.0,36.0,1.0,9.0,7.0
1,4.0,26434.0,2,1.0,honey/lemon cough drops,11.0,11.0,personal care,cold flu allergy,178520.0,36.0,1.0,9.0,7.0
2,4.0,25146.0,11,1.0,original orange juice,31.0,7.0,beverages,refrigerated,178520.0,36.0,1.0,9.0,7.0
3,4.0,10054.0,5,1.0,kellogg's nutri-grain apple cinnamon cereal,48.0,14.0,breakfast,breakfast bars pastries,178520.0,36.0,1.0,9.0,7.0
4,4.0,21351.0,6,1.0,nutri-grain soft baked strawberry cereal break...,48.0,14.0,breakfast,breakfast bars pastries,178520.0,36.0,1.0,9.0,7.0

In [60]:
# Verify that the `'order_hour_of_day'` and `'order_dow'` values in the `orders` tables are sensible
print(df["order_hour_of_day"].min(), df["order_hour_of_day"].max())
print(df["order_dow"].min(), df["order_dow"].max())

0.0 23.0
0.0 6.0

In [110]:
list(df["department"].unique())

['snacks',
 'personal care',
 'beverages',
 'breakfast',
 'bakery',
 'pantry',
 'dairy eggs',
 'produce',
 'canned goods',
 'frozen',
 'deli',
 'dry goods pasta',
 'meat seafood',
 nan,
 'bulk',
 'missing',
 'international',
 'household',
 'alcohol',
 'babies',
 'pets',
 'other']

In the list of department names, there is no department as groceries. Assumed it to be in "other".

In [117]:
# What time of day do people shop for groceries?
df_groceries = df.loc[df["department"] == "other", "order_hour_of_day"].value_counts()
df_groceries = df_groceries[df_groceries > 30].reset_index()
df_groceries

    order_hour_of_day  count
0                10.0    445
1                13.0    445
2                15.0    417
3                11.0    416
4                14.0    408
5                 9.0    394
6                16.0    392
7                12.0    381
8                17.0    356
9                18.0    287
10                8.0    233
11               19.0    207
12               20.0    146
13               21.0    128
14                7.0    125
15               22.0     91
16               23.0     67
17                6.0     55

In [121]:
# What day of the week do people shop for groceries?
df.loc[df["department"] == "other", "order_dow"].value_counts()

order_dow
1.0    866
0.0    846
2.0    727
6.0    694
5.0    684
4.0    641
3.0    633
Name: count, dtype: int64

In [64]:
df.head(2)

,order_id,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,department,aisle,user_id,order_number,order_dow,order_hour_of_day,days_since_prior_order
0,4.0,39758.0,3,1.0,chewy 25% low sugar chocolate chip granola,3.0,19.0,snacks,energy granola bars,178520.0,36.0,1.0,9.0,7.0
1,4.0,26434.0,2,1.0,honey/lemon cough drops,11.0,11.0,personal care,cold flu allergy,178520.0,36.0,1.0,9.0,7.0

In [122]:
# How long do people wait until placing another order?
df["days_since_prior_order"].value_counts()

days_since_prior_order
7.0     486288
30.0    435915
6.0     358181
5.0     299917
4.0     293440
8.0     271240
3.0     262609
2.0     208115
9.0     172669
14.0    144074
10.0    135731
1.0     131456
13.0    120587
11.0    117166
12.0    107344
15.0     95847
16.0     65049
0.0      64780
21.0     63561
17.0     53899
20.0     52184
19.0     49239
18.0     49181
22.0     44408
28.0     35685
23.0     32506
27.0     28644
24.0     28533
25.0     24892
26.0     24735
29.0     24110
Name: count, dtype: int64

In [123]:
# The difference in 'order_hour_of_day' distributions on Wednesdays and Saturdays
filtered_df = df[df["order_dow"].isin([2, 5])]
filtered_df.head()

,order_id,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,department,aisle,user_id,order_number,order_dow,order_hour_of_day,days_since_prior_order
33,19.0,41540.0,3,1.0,organic whole white mushrooms,83.0,4.0,produce,fresh vegetables,83009.0,7.0,5.0,17.0,13.0
34,19.0,24838.0,2,1.0,unsweetened almondmilk,91.0,16.0,dairy eggs,soy lactosefree,83009.0,7.0,5.0,17.0,13.0
35,19.0,42265.0,1,1.0,organic baby carrots,123.0,4.0,produce,packaged vegetables fruits,83009.0,7.0,5.0,17.0,13.0
55,48.0,11403.0,7,0.0,original barbeque sauce,5.0,13.0,pantry,marinades meat preparation,172786.0,5.0,2.0,0.0,30.0
56,48.0,42169.0,5,0.0,organic unrefined toasted sesame oil,19.0,13.0,pantry,oils vinegars,172786.0,5.0,2.0,0.0,30.0

In [124]:
grouped = filtered_df.groupby("order_dow")["order_hour_of_day"].value_counts()
grouped

order_dow  order_hour_of_day
2.0        10.0                 50750
           11.0                 50010
           14.0                 48291
           13.0                 48206
           16.0                 47169
           12.0                 46866
           15.0                 46543
           9.0                  45565
           17.0                 39157
           18.0                 31367
           8.0                  31290
           19.0                 23708
           20.0                 18190
           7.0                  17487
           21.0                 14452
           22.0                 11215
           23.0                  7640
           6.0                   5677
           0.0                   4436
           1.0                   2169
           5.0                   1697
           3.0                   1191
           2.0                   1107
           4.0                   1028
5.0        11.0                 50577
           10.0                 49472
           15.0                 48575
           14.0                 48464
           13.0                 47483
           16.0                 46197
           12.0                 45815
           9.0                  45121
           17.0                 37972
           8.0                  31539
           18.0                 31178
           19.0                 23259
           7.0                  18277
           20.0                 17771
           21.0                 14233
           22.0                 11128
           23.0                  8083
           6.0                   6380
           0.0                   4364
           5.0                   2043
           1.0                   2024
           2.0                   1074
           4.0                   1052
           3.0                    905
Name: count, dtype: int64

In [125]:
import plotly.express as px

In [127]:
fig = px.histogram(
    filtered_df,
    x="order_hour_of_day",
    color="order_dow",
    nbins=24,
    title="Distribution of Order Hours (Days 2 and 5)",
    labels={
        "order_hour_of_day": "Hour of Day",
        "order_dow": "Day of Week"
    }
)

fig.update_layout(xaxis=dict(dtick=1))
fig.show()

As it is obvious, the main orders are given after 6-7 am. Night orders are extremely less. It is most probably because of coinciding with sleeping hours.

In [131]:
# The distribution for the number of orders per customer
df_customer_orders = df.groupby("user_id")["order_id"].count()
df_customer_orders

user_id
2.0          26
4.0           3
5.0          12
6.0           5
7.0          14
           ...
206203.0     27
206206.0     21
206207.0     46
206208.0    125
206209.0     25
Name: order_id, Length: 157437, dtype: int64

In [132]:
df_customer_orders = df_customer_orders.reset_index()
df_customer_orders.rename(columns = {"order_id": "order_count"}, inplace = True)
df_customer_orders

         user_id  order_count
0            2.0           26
1            4.0            3
2            5.0           12
3            6.0            5
4            7.0           14
...          ...          ...
157432  206203.0           27
157433  206206.0           21
157434  206207.0           46
157435  206208.0          125
157436  206209.0           25

[157437 rows x 2 columns]

In [140]:
fig = px.histogram(
    df_customer_orders,
    x="order_count",
    nbins=20,
    title="Distribution of Orders per Customer",
    labels={
        "order_count": "Orders per Customer",
        "count": "Number of Customers"
    }
)

fig.update_layout(
    xaxis_title="Orders per Customer",
    yaxis_title="Number of Customers"
)

fig.show()

Number of customers decreases as the order numbers per customer increases. Most customers are ordered between 0-49 orders.

In [141]:
# The top 20 popular products
df_popular_products = df.groupby("product_name")["product_id"].count()
df_popular_products = df_popular_products.reset_index()
df_popular_products = df_popular_products.sort_values(by = "product_id", ascending = False)
df_popular_products.head(20)

                   product_name  product_id
3581                     banana       66050
3378     bag of organic bananas       53297
31104      organic strawberries       37039
28131      organic baby spinach       33971
29530      organic hass avocado       29773
28097           organic avocado       24689
21884               large lemon       21495
41770              strawberries       20018
22859                     limes       19690
31642        organic whole milk       19600
30565       organic raspberries       19197
31724      organic yellow onion       15898
29246            organic garlic       15292
31762          organic zucchini       14584
28295       organic blueberries       13879
11344            cucumber kirby       13675
29227        organic fuji apple       12544
29802             organic lemon       12232
2581   apple honeycrisp organic       11993
29377    organic grape tomatoes       11781

In [142]:
df.head()

,order_id,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,department,aisle,user_id,order_number,order_dow,order_hour_of_day,days_since_prior_order
0,4.0,39758.0,3,1.0,chewy 25% low sugar chocolate chip granola,3.0,19.0,snacks,energy granola bars,178520.0,36.0,1.0,9.0,7.0
1,4.0,26434.0,2,1.0,honey/lemon cough drops,11.0,11.0,personal care,cold flu allergy,178520.0,36.0,1.0,9.0,7.0
2,4.0,25146.0,11,1.0,original orange juice,31.0,7.0,beverages,refrigerated,178520.0,36.0,1.0,9.0,7.0
3,4.0,10054.0,5,1.0,kellogg's nutri-grain apple cinnamon cereal,48.0,14.0,breakfast,breakfast bars pastries,178520.0,36.0,1.0,9.0,7.0
4,4.0,21351.0,6,1.0,nutri-grain soft baked strawberry cereal break...,48.0,14.0,breakfast,breakfast bars pastries,178520.0,36.0,1.0,9.0,7.0

In [143]:
# Items which people typically buy in one order
df_one_time_order = df.groupby("order_id")["product_id"].count()
df_one_time_order = df_one_time_order.reset_index()
df_one_time_order.rename(columns = {"product_id": "product_count"}, inplace = True)
df_one_time_order

         order_id  product_count
0             4.0             13
1             9.0             15
2            11.0              5
3            19.0              3
4            20.0              8
...           ...            ...
478947  3421053.0              9
478948  3421058.0              0
478949  3421071.0              5
478950  3421077.0              4
478951  3421079.0              1

[478952 rows x 2 columns]

In [145]:

fig = px.histogram(
    df_one_time_order,
    x="product_count",
    nbins=20,
    title="Distribution of Products per Order",
    labels={
        "product_count": "Number of Products per Order",
        "count": "Number of Orders"
    }
)

fig.update_layout(
    xaxis_title="Number of Products per Order",
    yaxis_title="Number of Orders"
)

fig.show()

Orders contaning less number of products are dominant. As the products per order increases, this kind of orders are observed less.

In [153]:
# The top 20 items that are reordered most frequently
df_reordered_products = df[df["reordered"] == 1]
df_reordered_products = df_reordered_products.groupby("product_name")["product_id"].count()
df_reordered_products = df_reordered_products.reset_index()
df_reordered_products = df_reordered_products.sort_values(by = "product_id", ascending = False)
df_reordered_products.rename(columns = {"product_id": "product_count"}, inplace = True)
df_reordered_products.head(20)

                   product_name  product_count
2490                     banana          55763
2346     bag of organic bananas          44450
22929      organic strawberries          28639
20441      organic baby spinach          26233
21602      organic hass avocado          23629
20412           organic avocado          18743
23374        organic whole milk          16251
15903               large lemon          15044
22465       organic raspberries          14748
30837              strawberries          13945
16622                     limes          13327
23445      organic yellow onion          11145
21369            organic garlic          10411
23476          organic zucchini          10076
8289             cucumber kirby           9538
21353        organic fuji apple           8989
1789   apple honeycrisp organic           8836
20573       organic blueberries           8799
21824             organic lemon           8412
21582       organic half & half           8389

In [155]:
# For each product the proportion of reorders
df_reorders = df.groupby("product_id")["reordered"].mean()
df_reorders = df_reorders.reset_index()
df_reorders.rename(columns = {"reordered": "reorder_rate"}, inplace = True)
df_reorders

       product_id  reorder_rate
0             1.0      0.564286
1             2.0      0.000000
2             3.0      0.738095
3             4.0      0.510204
4             5.0           NaN
...           ...           ...
49689     49690.0      0.800000
49690     49691.0      0.430556
49691     49692.0      0.416667
49692     49693.0      0.440000
49693     49694.0      0.333333

[49694 rows x 2 columns]

In [162]:
# Mean function can be used for the same purpose.
reorder_rate = df.pivot_table(index = "product_id", columns = "reordered", values = "order_id", aggfunc = "count")
reorder_rate = reorder_rate.reset_index()
reorder_rate.rename(columns = {0: "not_reordered", 1: "reordered"}, inplace = True)
reorder_rate["reorder_rate"] = reorder_rate["reordered"] / (reorder_rate["not_reordered"] + reorder_rate["reordered"])
reorder_rate = reorder_rate[["product_id", "reorder_rate"]]
reorder_rate.head()

reordered  product_id  reorder_rate
0                 1.0      0.564286
1                 2.0           NaN
2                 3.0      0.738095
3                 4.0      0.510204
4                 7.0      0.500000

In [163]:
df.head()

,order_id,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,department,aisle,user_id,order_number,order_dow,order_hour_of_day,days_since_prior_order
0,4.0,39758.0,3,1.0,chewy 25% low sugar chocolate chip granola,3.0,19.0,snacks,energy granola bars,178520.0,36.0,1.0,9.0,7.0
1,4.0,26434.0,2,1.0,honey/lemon cough drops,11.0,11.0,personal care,cold flu allergy,178520.0,36.0,1.0,9.0,7.0
2,4.0,25146.0,11,1.0,original orange juice,31.0,7.0,beverages,refrigerated,178520.0,36.0,1.0,9.0,7.0
3,4.0,10054.0,5,1.0,kellogg's nutri-grain apple cinnamon cereal,48.0,14.0,breakfast,breakfast bars pastries,178520.0,36.0,1.0,9.0,7.0
4,4.0,21351.0,6,1.0,nutri-grain soft baked strawberry cereal break...,48.0,14.0,breakfast,breakfast bars pastries,178520.0,36.0,1.0,9.0,7.0

In [80]:
# For each customer, the proportion of their products reordered.
df_customer_reorders = df.groupby("user_id")["reordered"].mean()
df_customer_reorders = df_customer_reorders.reset_index()
df_customer_reorders.rename(columns = {"reordered": "reorder_rate"}, inplace = True)
df_customer_reorders

         user_id  reorder_rate
0            2.0      0.038462
1            4.0      0.000000
2            5.0      0.666667
3            6.0      0.000000
4            7.0      0.928571
...          ...           ...
157432  206203.0      0.222222
157433  206206.0      0.714286
157434  206207.0      0.891304
157435  206208.0      0.696000
157436  206209.0      0.320000

[157437 rows x 2 columns]

In [164]:
# The top 20 items that people put in their cards first
df_first_items = df.groupby("product_name")["add_to_cart_order"].min()
df_first_items = df_first_items.reset_index()
df_first_items.rename(columns = {"add_to_cart_order": "first_order"}, inplace = True)
df_first_items = df_first_items.sort_values(by = "first_order")
df_first_items.head(20)

                                          product_name  first_order
48316                                 zucchini noodles            1
48315        zucchini gingerbread carrot smart cookies            1
48312     zucchini banana & amaranth organic baby food            1
22                            0% greek strained yogurt            1
21                         0% fat vanilla greek yogurt            1
20                     0% fat superfruits greek yogurt            1
19                      0% fat strawberry greek yogurt            1
17                 0% fat organic greek vanilla yogurt            1
16                         0% fat greek yogurt vanilla            1
15      0% fat greek yogurt black cherry on the bottom            1
14                            0% fat free organic milk            1
13                       0% fat blueberry greek yogurt            1
12                  0% fat black cherry greek yogurt y            1
11     0 calorie strawberry dragonfruit water beverage            1
10            0 calorie fuji apple pear water beverage            1
9              0 calorie acai raspberry water beverage            1
32                                             1 liter            1
31                                 1 cup measuring cup            1
30                          1 apple + 1 pear fruit bar            1
29                         1 apple + 1 mango fruit bar            1